# Generated by Django 2.2.3 on 2020-01-16 03:12

import author.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='book_nm')),
                ('expr', models.IntegerField(verbose_name='author_exp')),
                ('age', models.IntegerField(verbose_name='author_age')),
                ('email', models.EmailField(max_length=254, validators=[author.models.checkforscpemail], verbose_name='author_email')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='pub_name')),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='book_nm')),
                ('price', models.FloatField(verbose_name='book_pr')),
                ('qty', models.IntegerField(validators=[author.models.check_valid_qty], verbose_name='book_qty')),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Publication')),
            ],
            options={
                'db_table': 'BOOK_INFO',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='author.Book'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('pincode', models.IntegerField(validators=[author.models.checkforpunepin], verbose_name='pincode')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
        ),
    ]
