# Generated by Django 2.2.3 on 2020-01-14 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='book_name')),
                ('price', models.FloatField(verbose_name='book_price')),
                ('category', models.CharField(max_length=100, verbose_name='book_cate')),
                ('publication', models.CharField(max_length=100, verbose_name='book_publ')),
                ('quantity', models.IntegerField(verbose_name='book_qty')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='author_name')),
                ('city', models.CharField(max_length=100, verbose_name='author_address')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='book.BookInfo')),
            ],
        ),
    ]
